package com.revenuedepartment.service;

public class ElementPlaceHolder  {
	public static String password = "password";
	public static String confirmPassowrd = "confirmPassowrd";
	public static String oldPassowrd = "oldPassowrd";
	public static String newPassword = "newPassword";
	public static String email = "email";
	public static String birthDate = "birthDate";
	public static String question = "question";
	public static String answer = "answer";
	public static String passportNo = "passportNo";
	public static String name = "name";
	public static String middleName = "middleName";
	public static String surname = "surname";
	public static String fatherName = "fatherName";
	public static String motherName = "motherName";
	public static String countryCode = "countryCode";
	public static String contractNo = "contractNo";
	public static String buildName = "buildName";
	public static String roomNo = "roomNo";
	public static String floorNo = "floorNo";
	public static String addressNo = "addressNo";
	public static String soi = "soi";
	public static String village = "village";
	public static String mooNo = "mooNo";
	public static String street = "street";
	public static String tambol = "tambol";
	public static String amphur = "amphur";
	public static String province = "province";
	public static String postcode = "postcode";
	public static String taxpayerStatus = "taxpayerStatus";
	public static String txpFatherPin = "txpFatherPin";
	public static String txpMotherPin = "txpMotherPin";
	public static String childStudy = "childStudy";
	public static String childNoStudy = "childNoStudy";
	public static String marryStatus = "marryStatus";
	public static String spouseStatus = "spouseStatus";
	public static String spouseNid = "spouseNid";
	public static String spouseBirthDate = "spouseBirthDate";
	public static String spouseName = "spouseName";
	public static String spouseSurname = "spouseSurname";
	public static String spousePassportNo = "spousePassportNo";
	public static String spouseCountryCode = "spouseCountryCode";
	public static String spouseFatherPin = "spouseFatherPin";
	public static String spouseMotherPin = "spouseMotherPin";
}
