package com.revenuedepartment.service;

/**
 * 
 * @author Narisa element
 */
public class JSONElement {
	// TODO obj
	public static String responseData = "responseData";
	public static String responseCode = "responseCode";
	public static String responseMessage = "responseMessage";
	public static String responseError = "responseError";
	public static String responseStatus = "responseStatus";
	public static String apiRefNo = "apiRefNo";
	public static String keys = "keys";
	public static String forms = "forms";
	public static String formName = "formName";
	public static String formData = "formData";
	public static String header = "header";
	public static String fields = "fields";
	public static String hidden = "hidden";
	public static String identify = "identify";
	public static String label = "label";
	public static String type = "type";
	public static String secure = "secure";
	public static String summary = "summary";
	public static String value = "value";
	public static String values = "values";
	public static String operate = "operate";
	public static String message = "message";
	public static String v1 = "v1";
	public static String v2 = "v2";
	public static String keyboardType = "keyboardType";
	public static String placeholder = "placeholder";
	public static String dependOn = "dependOn";
	public static String validate = "validate";
	public static String title = "title";
	public static String format = "format";
	public static String conditions = "conditions";
	public static String maximum = "maximum";
	
	// TODO keys
	public static String assblInc = "assblInc";
	public static String incomePayer = "incomePayer";
	public static String exAge65 = "exAge65";
	public static String assblIncAfAge65 = "assblIncAfAge65";
	public static String expfPd1 = "expfPd1";
	public static String expfPd2 = "expfPd2";
	public static String qpdInc = "qpdInc";
	public static String pvdAmtOfExcept = "pvdAmtOfExcept";
	public static String sumExeInc = "sumExeInc";
	public static String txpAllw = "txpAllw";
	public static String spoAllw = "spoAllw";
	public static String childNoStudy = "childNoStudy";
	public static String childNoStudyAmt = "childNoStudyAmt";
	public static String childStudy = "childStudy";
	public static String childStudyAmt = "childStudyAmt";
	public static String txpFatherPin = "txpFatherPin";
	public static String txpFatherAmt = "txpFatherAmt";
	public static String txpMotherPin = "txpMotherPin";
	public static String txpMotherAmt = "txpMotherAmt";
	public static String spouseFatherPin = "spouseFatherPin";
	public static String spouseFatherAmt = "spouseFatherAmt";
	public static String spouseMotherPin = "spouseMotherPin";
	public static String spouseMotherAmt = "spouseMotherAmt";
	public static String insFaMoAmt = "insFaMoAmt";
	public static String txpFaPinIns = "txpFaPinIns";
	public static String txpMoPinIns = "txpMoPinIns";
	public static String spoFaPinIns = "spoFaPinIns";
	public static String spoMoPinIns = "spoMoPinIns";
	public static String insAmt = "insAmt";
	public static String spoInsAmt = "spoInsAmt";
	public static String retireInsAmt = "retireInsAmt";
	public static String pvdAmtOfAllw = "pvdAmtOfAllw";
	public static String expfPd3 = "expfPd3";
	public static String expfPd4 = "expfPd4";
	public static String intLoan = "intLoan";
	public static String otherAmt = "otherAmt";
	public static String ssfAmt = "ssfAmt";
	public static String incBfExp = "incBfExp";
	public static String expense = "expense";
	public static String incDedExp = "incDedExp";
	public static String sumAllowance = "sumAllowance";
	public static String incBfEdu = "incBfEdu";
	public static String eduAmt = "eduAmt";
	public static String incBfDon = "incBfDon";
	public static String donAmt = "donAmt";
	public static String netIncome = "netIncome";
	public static String propertyPrice = "propertyPrice";
	public static String propertyAmt = "propertyAmt";
	public static String whtTax = "whtTax";
	public static String paidTax = "paidTax";
	
	//authen
	public static String passportNo = "passportNo";
	public static String countryCode = "countryCode";
	public static String email = "email";
	public static String titleName = "titleName";
	public static String birthDate = "birthDate";
	public static String contractNo = "contractNo";
	public static String indcForm = "indcForm";
	public static String spouseBirthDate = "spouseBirthDate";
	public static String spousePassportNo = "spousePassportNo";
	public static String spouseCountryCode = "spouseCountryCode";
	public static String nid = "nid";
	public static String name = "name";
	public static String surname = "surname";
	public static String buildName = "buildName";
	public static String roomNo = "roomNo";
	public static String floorNo = "floorNo";
	public static String addressNo = "addressNo";
	public static String soi = "soi";
	public static String village = "village";
	public static String mooNo = "mooNo";
	public static String street = "street";
	public static String tambol = "tambol";
	public static String amphur = "amphur";
	public static String province = "province";
	public static String postcode = "postcode";
	public static String taxpayerStatus = "taxpayerStatus";
	public static String spouseStatus = "spouseStatus";
	public static String marryStatus = "marryStatus";
	public static String spouseNid = "spouseNid";
	public static String spouseName = "spouseName";
	public static String spouseSurname = "spouseSurname";
	public static String authenKey = "authenKey";
	public static String thaiNation = "thaiNation";
	public static String taxpayerHash = "taxpayerHash";
	public static String spouseHash = "spouseHash";
	public static String marryHash = "marryHash";
	public static String lastAccessed = "lastAccessed";
}
